[package]
name = "spwn"
version = "0.0.85"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.1"
ariadne = "0.1.5"
slotmap = "1.0.6"
ansi_term = "0.12.1"
regex = "1.5.6"
thiserror = "1.0.31"
ahash = "0.7.6"
serde = { version = "1.0.138", features = ["derive"] }
bincode = "1.3.3"
lz4-compression = "0.7.0"
yazi = "0.1.4"